# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNN15' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNN15

  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'

  target 'RNN15-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNN15Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
