# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNN10' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNN10
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'



  target 'RNN10Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
