# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNN02' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNN02

  target 'RNN02-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNN02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
